"""Initial schema: tenancy, identity, documents, retrieval index, jobs, audit.

Tables are autogenerated from the ORM; everything security-relevant (RLS policies, roles,
grants, SECURITY DEFINER lookups, immutability triggers, HNSW index) comes from
``migrations/docassist_migration_security.py`` so it is reviewable in one place.

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 00:00:08.939976
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

from docassist_migration_security import (  # noqa: E402  (helper module next to env.py)
    EMBEDDING_DIMENSIONS,
    security_downgrade,
    security_prelude,
    security_upgrade,
)

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    security_prelude()
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_chain_heads',
    sa.Column('chain_key', sa.UUID(), nullable=False),
    sa.Column('last_seq', sa.BigInteger(), nullable=False),
    sa.Column('last_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('anchor_seq', sa.BigInteger(), nullable=False),
    sa.Column('anchor_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chain_key', name=op.f('pk_audit_chain_heads'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('actor_ip_prefix', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('seal_seq', sa.BigInteger(), nullable=True),
    sa.Column('prev_hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('hash', sa.LargeBinary(length=32), nullable=True),
    sa.Column('sealed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("outcome IN ('success', 'denied', 'failure')", name=op.f('ck_audit_events_outcome')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_events_action', 'audit_events', ['organization_id', 'action', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_actor', 'audit_events', ['organization_id', 'actor_user_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_org_time', 'audit_events', ['organization_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_events_unsealed', 'audit_events', ['id'], unique=False, postgresql_where=sa.text('hash IS NULL'))
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$'", name=op.f('ck_organizations_slug_format')),
    sa.CheckConstraint("status IN ('active', 'suspended')", name=op.f('ck_organizations_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('departments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=63), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$'", name=op.f('ck_departments_slug_format')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_departments_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_departments')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_departments_organization_id_id')),
    sa.UniqueConstraint('organization_id', 'slug', name=op.f('uq_departments_organization_id_slug'))
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.SmallInteger(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('idempotency_key', sa.String(length=200), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed', 'dead', 'cancelled')", name=op.f('ck_jobs_status')),
    sa.CheckConstraint('attempts >= 0 AND max_attempts >= 1', name=op.f('ck_jobs_attempts')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_jobs_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_jobs_idempotency_key'))
    )
    op.create_index('ix_jobs_claimable', 'jobs', ['priority', 'run_after'], unique=False, postgresql_where=sa.text("status = 'queued'"))
    op.create_index('ix_jobs_org_created', 'jobs', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_jobs_running_lease', 'jobs', ['locked_until'], unique=False, postgresql_where=sa.text("status = 'running'"))
    op.create_table('llm_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('task', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_llm_usage_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_llm_usage'))
    )
    op.create_index('ix_llm_usage_org_time', 'llm_usage', ['organization_id', 'created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('clearance', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('lockout_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret_enc', sa.LargeBinary(), nullable=True),
    sa.Column('mfa_last_used_step', sa.BigInteger(), nullable=True),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(role = 'platform_admin') = (organization_id IS NULL)", name=op.f('ck_users_platform_admin_has_no_org')),
    sa.CheckConstraint("clearance IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')", name=op.f('ck_users_clearance')),
    sa.CheckConstraint("role IN ('platform_admin', 'organization_admin', 'department_manager', 'employee', 'auditor')", name=op.f('ck_users_role')),
    sa.CheckConstraint("status IN ('active', 'disabled')", name=op.f('ck_users_status')),
    sa.CheckConstraint('email = lower(email)', name=op.f('ck_users_email_lowercase')),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_users_organization_id_id'))
    )
    op.create_index('ix_users_org_role', 'users', ['organization_id', 'role'], unique=False)
    op.create_table('auth_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoke_reason', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('ip_prefix', sa.String(length=64), nullable=True),
    sa.Column('mfa_verified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auth_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_sessions'))
    )
    op.create_index('ix_auth_sessions_user', 'auth_sessions', ['user_id', 'revoked_at'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'user_id'], ['users.organization_id', 'users.id'], name=op.f('fk_conversations_organization_id_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_conversations_organization_id_id'))
    )
    op.create_index('ix_conversations_user', 'conversations', ['organization_id', 'user_id', 'updated_at'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('doc_type', sa.String(length=16), nullable=False),
    sa.Column('doc_type_source', sa.String(length=16), nullable=False),
    sa.Column('doc_type_confidence', sa.Float(), nullable=True),
    sa.Column('allowed_roles', postgresql.ARRAY(sa.String(length=32)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('version_count', sa.Integer(), nullable=False),
    sa.Column('suggested_classification', sa.String(length=16), nullable=True),
    sa.Column('sensitivity_signals', postgresql.ARRAY(sa.String(length=32)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('retention_until', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("classification IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')", name=op.f('ck_documents_classification')),
    sa.CheckConstraint("doc_type IN ('contract', 'invoice', 'policy', 'hr', 'technical', 'financial', 'legal', 'report', 'other')", name=op.f('ck_documents_doc_type')),
    sa.CheckConstraint("status IN ('processing', 'ready', 'failed', 'quarantined', 'deleted')", name=op.f('ck_documents_status')),
    sa.CheckConstraint("suggested_classification IS NULL OR suggested_classification IN ('PUBLIC', 'INTERNAL', 'CONFIDENTIAL', 'RESTRICTED')", name=op.f('ck_documents_suggested_classification')),
    sa.CheckConstraint('cardinality(tags) <= 20', name=op.f('ck_documents_tag_limit')),
    sa.ForeignKeyConstraint(['organization_id', 'department_id'], ['departments.organization_id', 'departments.id'], name=op.f('fk_documents_organization_id_department_id_departments'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id', 'owner_id'], ['users.organization_id', 'users.id'], name=op.f('fk_documents_organization_id_owner_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_documents_organization_id_organizations'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_documents_organization_id_id'))
    )
    op.create_index('ix_documents_org_created', 'documents', ['organization_id', 'created_at'], unique=False)
    op.create_index('ix_documents_org_department', 'documents', ['organization_id', 'department_id'], unique=False)
    op.create_index('ix_documents_org_owner', 'documents', ['organization_id', 'owner_id'], unique=False)
    op.create_index('ix_documents_org_status', 'documents', ['organization_id', 'status', 'classification'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('download_count', sa.Integer(), nullable=False),
    sa.Column('last_downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("format IN ('csv', 'json')", name=op.f('ck_exports_format')),
    sa.CheckConstraint("status IN ('pending', 'ready', 'failed', 'expired')", name=op.f('ck_exports_status')),
    sa.ForeignKeyConstraint(['organization_id', 'user_id'], ['users.organization_id', 'users.id'], name=op.f('fk_exports_organization_id_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exports')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_exports_organization_id_id'))
    )
    op.create_index('ix_exports_user', 'exports', ['organization_id', 'user_id', 'created_at'], unique=False)
    op.create_table('mfa_challenges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_mfa_challenges_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mfa_challenges')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_mfa_challenges_token_hash'))
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_password_reset_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('user_departments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('department_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'department_id'], ['departments.organization_id', 'departments.id'], name=op.f('fk_user_departments_organization_id_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'user_id'], ['users.organization_id', 'users.id'], name=op.f('fk_user_departments_organization_id_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'department_id', name=op.f('pk_user_departments'))
    )
    op.create_index('ix_user_departments_department', 'user_departments', ['organization_id', 'department_id'], unique=False)
    op.create_table('document_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('grantee_type', sa.String(length=16), nullable=False),
    sa.Column('grantee_user_id', sa.UUID(), nullable=True),
    sa.Column('grantee_department_id', sa.UUID(), nullable=True),
    sa.Column('grantee_role', sa.String(length=32), nullable=True),
    sa.Column('permission', sa.String(length=16), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(grantee_type = 'user' AND grantee_user_id IS NOT NULL AND grantee_department_id IS NULL AND grantee_role IS NULL) OR (grantee_type = 'department' AND grantee_department_id IS NOT NULL AND grantee_user_id IS NULL AND grantee_role IS NULL) OR (grantee_type = 'role' AND grantee_role IS NOT NULL AND grantee_user_id IS NULL AND grantee_department_id IS NULL)", name=op.f('ck_document_grants_grantee_shape')),
    sa.CheckConstraint("grantee_role IS NULL OR grantee_role <> 'platform_admin'", name=op.f('ck_document_grants_no_platform_grants')),
    sa.CheckConstraint("grantee_type IN ('user', 'department', 'role')", name=op.f('ck_document_grants_grantee_type')),
    sa.CheckConstraint("permission IN ('read', 'manage')", name=op.f('ck_document_grants_permission')),
    sa.ForeignKeyConstraint(['organization_id', 'document_id'], ['documents.organization_id', 'documents.id'], name=op.f('fk_document_grants_organization_id_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'grantee_department_id'], ['departments.organization_id', 'departments.id'], name=op.f('fk_document_grants_organization_id_grantee_department_id_departments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'grantee_user_id'], ['users.organization_id', 'users.id'], name=op.f('fk_document_grants_organization_id_grantee_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_grants'))
    )
    op.create_index('ix_document_grants_document', 'document_grants', ['organization_id', 'document_id'], unique=False)
    op.create_index('ix_document_grants_user', 'document_grants', ['organization_id', 'grantee_user_id'], unique=False)
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('extension', sa.String(length=10), nullable=False),
    sa.Column('declared_mime', sa.String(length=127), nullable=True),
    sa.Column('detected_mime', sa.String(length=127), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('char_count', sa.Integer(), nullable=True),
    sa.Column('chunk_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('security_findings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('semantic_indexed', sa.Boolean(), nullable=False),
    sa.Column('needs_ocr', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_detail', sa.String(length=500), nullable=True),
    sa.Column('change_note', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("sha256 ~ '^[0-9a-f]{64}$'", name=op.f('ck_document_versions_sha256_hex')),
    sa.CheckConstraint("status IN ('uploaded', 'processing', 'indexed', 'failed', 'quarantined')", name=op.f('ck_document_versions_status')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_document_versions_size_non_negative')),
    sa.ForeignKeyConstraint(['organization_id', 'document_id'], ['documents.organization_id', 'documents.id'], name=op.f('fk_document_versions_organization_id_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_versions')),
    sa.UniqueConstraint('document_id', 'version_number', name=op.f('uq_document_versions_document_id_version_number')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_document_versions_organization_id_id')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_document_versions_storage_key'))
    )
    op.create_index('ix_document_versions_org_sha', 'document_versions', ['organization_id', 'sha256'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name=op.f('ck_messages_role')),
    sa.ForeignKeyConstraint(['organization_id', 'conversation_id'], ['conversations.organization_id', 'conversations.id'], name=op.f('fk_messages_organization_id_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_conversation', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('token_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['auth_sessions.id'], name=op.f('fk_refresh_tokens_session_id_auth_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_session_id'), 'refresh_tokens', ['session_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_start', sa.Integer(), nullable=True),
    sa.Column('page_end', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=300), nullable=True),
    sa.Column('heading_path', postgresql.ARRAY(sa.String(length=300)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('block_types', postgresql.ARRAY(sa.String(length=16)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('injection_score', sa.Float(), nullable=False),
    sa.Column('injection_flags', postgresql.ARRAY(sa.String(length=48)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('pii_types', postgresql.ARRAY(sa.String(length=24)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(section, '')), 'A') || setweight(to_tsvector('english', content), 'B') || setweight(to_tsvector('simple', content), 'C')", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'document_id'], ['documents.organization_id', 'documents.id'], name=op.f('fk_document_chunks_organization_id_document_id_documents'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id', 'version_id'], ['document_versions.organization_id', 'document_versions.id'], name=op.f('fk_document_chunks_organization_id_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('organization_id', 'id', name=op.f('uq_document_chunks_organization_id_id')),
    sa.UniqueConstraint('version_id', 'chunk_index', name=op.f('uq_document_chunks_version_id_chunk_index'))
    )
    op.create_index('ix_document_chunks_doc', 'document_chunks', ['organization_id', 'document_id', 'version_id'], unique=False)
    op.create_index('ix_document_chunks_tsv', 'document_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('extracted_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=64), nullable=False),
    sa.Column('value_text', sa.String(length=1000), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('value_number', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('evidence', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('rules', 'llm')", name=op.f('ck_extracted_fields_method')),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_extracted_fields_confidence_range')),
    sa.ForeignKeyConstraint(['organization_id', 'version_id'], ['document_versions.organization_id', 'document_versions.id'], name=op.f('fk_extracted_fields_organization_id_version_id_document_versions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extracted_fields'))
    )
    op.create_index('ix_extracted_fields_lookup', 'extracted_fields', ['organization_id', 'field', 'value_date'], unique=False)
    op.create_index('ix_extracted_fields_version', 'extracted_fields', ['organization_id', 'version_id'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('embedding', Vector(EMBEDDING_DIMENSIONS), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id', 'chunk_id'], ['document_chunks.organization_id', 'document_chunks.id'], name=op.f('fk_chunk_embeddings_organization_id_chunk_id_document_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_chunk_embeddings'))
    )
    op.create_index('ix_chunk_embeddings_doc', 'chunk_embeddings', ['organization_id', 'document_id'], unique=False)
    # ### end Alembic commands ###
    security_upgrade()


def downgrade() -> None:
    op.drop_constraint("fk_documents_current_version", "documents", type_="foreignkey")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_embeddings_doc', table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    op.drop_index('ix_extracted_fields_version', table_name='extracted_fields')
    op.drop_index('ix_extracted_fields_lookup', table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index('ix_document_chunks_tsv', table_name='document_chunks', postgresql_using='gin')
    op.drop_index('ix_document_chunks_doc', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_refresh_tokens_session_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_messages_conversation', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_document_versions_org_sha', table_name='document_versions')
    op.drop_table('document_versions')
    op.drop_index('ix_document_grants_user', table_name='document_grants')
    op.drop_index('ix_document_grants_document', table_name='document_grants')
    op.drop_table('document_grants')
    op.drop_index('ix_user_departments_department', table_name='user_departments')
    op.drop_table('user_departments')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_table('mfa_challenges')
    op.drop_index('ix_exports_user', table_name='exports')
    op.drop_table('exports')
    op.drop_index('ix_documents_org_status', table_name='documents')
    op.drop_index('ix_documents_org_owner', table_name='documents')
    op.drop_index('ix_documents_org_department', table_name='documents')
    op.drop_index('ix_documents_org_created', table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_conversations_user', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_auth_sessions_user', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    op.drop_index('ix_users_org_role', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_llm_usage_org_time', table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index('ix_jobs_running_lease', table_name='jobs', postgresql_where=sa.text("status = 'running'"))
    op.drop_index('ix_jobs_org_created', table_name='jobs')
    op.drop_index('ix_jobs_claimable', table_name='jobs', postgresql_where=sa.text("status = 'queued'"))
    op.drop_table('jobs')
    op.drop_table('departments')
    op.drop_table('organizations')
    op.drop_index('ix_audit_events_unsealed', table_name='audit_events', postgresql_where=sa.text('hash IS NULL'))
    op.drop_index('ix_audit_events_org_time', table_name='audit_events')
    op.drop_index('ix_audit_events_actor', table_name='audit_events')
    op.drop_index('ix_audit_events_action', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('audit_chain_heads')
    # ### end Alembic commands ###
    security_downgrade()
