"""Encrypted object storage.

* Object keys are generated by the server (``<org>/<xx>/<uuid>``) - no user input ever
  reaches a filesystem path, and resolved paths are re-checked to stay under the root.
* Every object is encrypted with its own data key (see :mod:`docassist.security.crypto`)
  and bound to a *context* (organisation + object kind + object id): a blob copied onto
  another record's key fails authentication instead of disclosing content.
* Writes go to a temp file in the same directory and are atomically renamed; files are
  created with owner-only permissions.

Production deployments can implement :class:`ObjectStorage` for S3/Azure Blob (with
server-side encryption on top of this client-side layer) without touching callers.
"""

from __future__ import annotations

import asyncio
import os
import uuid
from collections.abc import AsyncIterator, Iterator
from pathlib import Path
from typing import Protocol

from docassist.core.ids import uuid7
from docassist.security.crypto import KeyRing, StreamEncryptor, decrypt_stream

_READ_CHUNK = 256 * 1024


class StorageError(Exception):
    pass


def storage_context(org_id: uuid.UUID, kind: str, object_id: uuid.UUID) -> bytes:
    """Associated data that binds ciphertext to exactly one record."""
    return f"org:{org_id}|{kind}:{object_id}".encode()


def new_object_key(org_id: uuid.UUID) -> str:
    oid = uuid7().hex
    return f"{org_id.hex}/{oid[-2:]}/{oid}"


class ObjectStorage(Protocol):
    async def put_stream(self, key: str, chunks: AsyncIterator[bytes], context: bytes) -> int: ...

    async def put_bytes(self, key: str, data: bytes, context: bytes) -> int: ...

    def iter_plaintext(self, key: str, context: bytes) -> Iterator[bytes]: ...

    async def read_bytes(self, key: str, context: bytes, max_bytes: int) -> bytes: ...

    async def delete(self, key: str) -> None: ...

    async def exists(self, key: str) -> bool: ...


class LocalEncryptedStorage:
    def __init__(self, root: Path, ring: KeyRing) -> None:
        self._root = root.resolve()
        self._root.mkdir(parents=True, exist_ok=True)
        self._ring = ring

    def _path(self, key: str) -> Path:
        parts = key.split("/")
        if len(parts) != 3 or not all(p and p.isalnum() for p in parts):
            raise StorageError("invalid object key")
        path = (self._root / parts[0] / parts[1] / parts[2]).resolve()
        if not path.is_relative_to(self._root):
            raise StorageError("object key escapes storage root")
        return path

    async def put_stream(self, key: str, chunks: AsyncIterator[bytes], context: bytes) -> int:
        path = self._path(key)
        path.parent.mkdir(parents=True, exist_ok=True)
        tmp = path.with_name(path.name + ".part")
        encryptor = StreamEncryptor(self._ring, context)
        written = 0
        fd = os.open(tmp, os.O_WRONLY | os.O_CREAT | os.O_EXCL | getattr(os, "O_BINARY", 0), 0o600)
        try:
            with os.fdopen(fd, "wb") as handle:
                handle.write(encryptor.header)
                written += len(encryptor.header)
                async for chunk in chunks:
                    sealed = encryptor.update(chunk)
                    if sealed:
                        await asyncio.to_thread(handle.write, sealed)
                        written += len(sealed)
                final = encryptor.finalize()
                handle.write(final)
                written += len(final)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(tmp, path)
        except BaseException:
            tmp.unlink(missing_ok=True)
            raise
        return written

    async def put_bytes(self, key: str, data: bytes, context: bytes) -> int:
        async def one() -> AsyncIterator[bytes]:
            yield data

        return await self.put_stream(key, one(), context)

    def iter_plaintext(self, key: str, context: bytes) -> Iterator[bytes]:
        path = self._path(key)
        try:
            handle = path.open("rb")
        except FileNotFoundError as exc:
            raise StorageError("object not found") from exc
        with handle:
            yield from decrypt_stream(self._ring, handle, context)

    async def read_bytes(self, key: str, context: bytes, max_bytes: int) -> bytes:
        def _read() -> bytes:
            out = bytearray()
            for chunk in self.iter_plaintext(key, context):
                out += chunk
                if len(out) > max_bytes:
                    raise StorageError("object larger than allowed")
            return bytes(out)

        return await asyncio.to_thread(_read)

    async def delete(self, key: str) -> None:
        await asyncio.to_thread(self._path(key).unlink, True)

    async def exists(self, key: str) -> bool:
        return await asyncio.to_thread(self._path(key).exists)
