"""Upload validation: filename hygiene, bounded spooling, content sniffing, ZIP inspection.

Every upload is treated as hostile. This module decides whether the bytes are *what they
claim to be*; :mod:`docassist.documents.scanning` then decides whether they are *safe*.

* :func:`sanitize_filename` - the client's filename is display metadata only (storage keys are
  generated by the server), but it still reaches UIs, audit trails and ``Content-Disposition``
  headers, so it is reduced to a clean, bounded basename.
* :func:`spool_upload` - copies the request stream into a :class:`SpooledUpload` while hashing
  it (SHA-256) and enforcing the size limit *as bytes arrive*: the upload is aborted with
  :class:`~docassist.core.errors.PayloadTooLarge` at the first chunk that crosses the limit.
  Small uploads stay in memory (their plaintext never touches the disk unencrypted); larger
  ones roll over to a private :func:`tempfile.mkstemp` file (mode 0600 on POSIX) that
  :meth:`SpooledUpload.close` always deletes.
* :func:`sniff` - magic bytes decide the type and the extension must agree with them; the
  client-declared MIME type is recorded by the caller but never trusted.
* :func:`inspect_zip` - OOXML packages are ZIP archives, so zip bombs, path traversal,
  encrypted/symlink/nested entries and macro-enabled package types are rejected using archive
  *metadata* only (nothing is extracted to disk). CPython's :mod:`zipfile` never returns more
  than an entry's declared size, so the declared sizes checked here also bound what any
  in-process consumer can inflate.
* :func:`validate_text` - text formats must be UTF-8 (BOM optional) or BOM-marked UTF-16,
  without NUL characters and with a low proportion of control characters.
"""

from __future__ import annotations

import asyncio
import codecs
import hashlib
import io
import os
import re
import struct
import tempfile
import zipfile
from collections.abc import AsyncIterator, Iterable, Iterator
from dataclasses import dataclass
from pathlib import Path
from types import TracebackType
from typing import BinaryIO, Final, Literal

import defusedxml.ElementTree as SafeElementTree
from defusedxml.common import DefusedXmlException

from docassist.core.errors import (
    PayloadTooLarge,
    RejectedContent,
    UnsupportedMediaType,
    ValidationFailed,
)
from docassist.core.logging import get_logger
from docassist.core.text import sanitize_text

log = get_logger(__name__)

MIME_TYPES: Final[dict[str, str]] = {
    "pdf": "application/pdf",
    "docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    "xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "csv": "text/csv",
    "txt": "text/plain",
    "md": "text/markdown",
}
"""Canonical MIME type per supported extension (what downloads are served as)."""

TEXT_EXTENSIONS: Final = frozenset({"csv", "md", "txt"})
OOXML_EXTENSIONS: Final = frozenset({"docx", "xlsx"})

HEAD_BYTES: Final = 8 * 1024
"""Bytes kept from the start of every upload for magic-byte sniffing."""

DEFAULT_MEMORY_SPOOL_BYTES: Final = 1024 * 1024
"""Uploads up to this size are spooled in memory; larger ones go to a private temp file."""

READ_CHUNK_BYTES: Final = 256 * 1024

Family = Literal["pdf", "ooxml", "text"]


# --------------------------------------------------------------------------- #
# Error helpers - every rejection carries a stable machine-readable reason
# --------------------------------------------------------------------------- #
def _rejected(reason: str, message: str) -> RejectedContent:
    return RejectedContent(message, internal_detail=reason, extra={"reason": reason})


def _unsupported(reason: str, message: str) -> UnsupportedMediaType:
    return UnsupportedMediaType(message, internal_detail=reason, extra={"reason": reason})


# --------------------------------------------------------------------------- #
# Filenames
# --------------------------------------------------------------------------- #
MAX_FILENAME_CHARS: Final = 150
FALLBACK_FILENAME: Final = "document"
_MAX_RAW_FILENAME_CHARS = 1024
_PATH_SEPARATORS = re.compile(r"[/\\]")
_EXTENSION_RE = re.compile(r"[A-Za-z0-9]{1,10}")
_UNSAFE_FILENAME_CHARS = re.compile(r'[<>:"|?*;]')
_WINDOWS_RESERVED = frozenset(
    {"con", "prn", "aux", "nul"}
    | {f"com{i}" for i in range(1, 10)}
    | {f"lpt{i}" for i in range(1, 10)}
)


def _basename(name: str) -> str:
    return _PATH_SEPARATORS.split(name)[-1]


def sanitize_filename(name: str) -> str:
    """Reduce a client-supplied filename to a safe display name.

    Basename only (both ``/`` and ``\\`` count as separators, before *and* after NFKC
    normalisation, which can turn look-alikes such as a fullwidth solidus into a real one);
    invisible, bidi-override and Unicode-tag characters removed; control characters and
    characters reserved by common filesystems replaced; whitespace collapsed; leading and
    trailing dots/spaces stripped; Windows device names defused; at most
    :data:`MAX_FILENAME_CHARS` characters with the extension kept. Falls back to
    ``"document"`` (plus the extension, if any) when nothing usable remains.
    """
    raw = _basename(name or "")[-_MAX_RAW_FILENAME_CHARS:]
    cleaned, _report = sanitize_text(raw)
    cleaned = _basename(cleaned)
    cleaned = _UNSAFE_FILENAME_CHARS.sub("_", cleaned)
    cleaned = " ".join(cleaned.split())
    stem, dot, ext = cleaned.rpartition(".")
    if not dot or not _EXTENSION_RE.fullmatch(ext):
        stem, ext = cleaned, ""
    stem = stem.strip(" .")
    ext = ext.lower()
    if stem.split(".", 1)[0].strip().lower() in _WINDOWS_RESERVED:
        stem = "_" + stem
    budget = MAX_FILENAME_CHARS - (len(ext) + 1 if ext else 0)
    stem = stem[:budget].rstrip(" .") or FALLBACK_FILENAME
    return f"{stem}.{ext}" if ext else stem


def extension_of(filename: str) -> str:
    """Lower-cased extension of an (already sanitised) filename, or ``""``."""
    _stem, dot, ext = filename.rpartition(".")
    return ext.lower() if dot and _EXTENSION_RE.fullmatch(ext) else ""


# --------------------------------------------------------------------------- #
# Spooling
# --------------------------------------------------------------------------- #
class SpooledUpload:
    """The bytes of one upload: in memory up to a threshold, else in a private temp file.

    Use it as a context manager (or call :meth:`close`) - the temp file, if any, is deleted.
    :meth:`open` returns an *independent* reader each time, so validators and scanners can
    run one after another without sharing a file position.
    """

    def __init__(self, *, memory_limit: int, temp_dir: Path | None) -> None:
        self._memory_limit = memory_limit
        self._temp_dir = temp_dir
        self._buffer: bytearray | None = bytearray()
        self._path: Path | None = None
        self._file: BinaryIO | None = None
        self._hash = hashlib.sha256()
        self._digest: str | None = None
        self._head = bytearray()
        self._size = 0

    # ------------------------------------------------------------------ state
    @property
    def size(self) -> int:
        return self._size

    @property
    def head(self) -> bytes:
        """The first :data:`HEAD_BYTES` bytes (for magic-byte sniffing)."""
        return bytes(self._head)

    @property
    def sha256(self) -> str:
        if self._digest is None:
            raise RuntimeError("upload is not sealed yet")
        return self._digest

    @property
    def path(self) -> Path | None:
        """Temp file path if the upload rolled over to disk, else ``None``."""
        return self._path

    @property
    def in_memory(self) -> bool:
        return self._path is None

    # ---------------------------------------------------------------- writing
    async def write(self, data: bytes) -> None:
        if self._digest is not None:
            raise RuntimeError("upload is sealed")
        self._hash.update(data)
        if len(self._head) < HEAD_BYTES:
            self._head += data[: HEAD_BYTES - len(self._head)]
        self._size += len(data)
        if self._buffer is not None and len(self._buffer) + len(data) <= self._memory_limit:
            self._buffer += data
            return
        handle = self._file
        if handle is None:
            handle = await asyncio.to_thread(self._roll_over)
        await asyncio.to_thread(handle.write, data)

    def _roll_over(self) -> BinaryIO:
        directory: str | None = None
        if self._temp_dir is not None:
            self._temp_dir.mkdir(parents=True, exist_ok=True, mode=0o700)
            directory = str(self._temp_dir)
        # mkstemp creates the file with O_EXCL and mode 0600 (owner-only on POSIX).
        fd, name = tempfile.mkstemp(prefix="docassist-upload-", suffix=".part", dir=directory)
        self._path = Path(name)
        handle = os.fdopen(fd, "w+b")
        self._file = handle
        if self._buffer:
            handle.write(self._buffer)
        self._buffer = None
        return handle

    def seal(self) -> None:
        """Finish writing: flush the temp file and fix the digest."""
        if self._digest is not None:
            return
        if self._file is not None:
            self._file.flush()
        self._digest = self._hash.hexdigest()

    # ---------------------------------------------------------------- reading
    def open(self) -> BinaryIO:
        """A fresh, independent binary reader positioned at the start."""
        if self._path is not None:
            return self._path.open("rb")
        return io.BytesIO(bytes(self._buffer or b""))

    def iter_chunks(self, chunk_size: int = READ_CHUNK_BYTES) -> Iterator[bytes]:
        with self.open() as handle:
            while chunk := handle.read(chunk_size):
                yield chunk

    async def aiter_chunks(self, chunk_size: int = READ_CHUNK_BYTES) -> AsyncIterator[bytes]:
        """Async chunk stream (file reads run in a worker thread)."""
        with self.open() as handle:
            while chunk := await asyncio.to_thread(handle.read, chunk_size):
                yield chunk

    # --------------------------------------------------------------- cleanup
    def close(self) -> None:
        """Release memory and delete the temp file (idempotent)."""
        self._buffer = None
        if self._file is not None:
            try:
                self._file.close()
            except OSError:
                log.warning("upload_spool_close_failed")
            self._file = None
        if self._path is not None:
            try:
                self._path.unlink(missing_ok=True)
            except OSError:
                log.exception("upload_spool_delete_failed")
            self._path = None

    def __enter__(self) -> SpooledUpload:
        return self

    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        tb: TracebackType | None,
    ) -> None:
        self.close()


async def spool_upload(
    stream: AsyncIterator[bytes],
    *,
    max_bytes: int,
    temp_dir: Path | None = None,
    memory_limit: int = DEFAULT_MEMORY_SPOOL_BYTES,
) -> SpooledUpload:
    """Copy ``stream`` into a sealed :class:`SpooledUpload`, enforcing ``max_bytes``.

    Raises :class:`PayloadTooLarge` as soon as a chunk would cross the limit (the rest of the
    stream is never read) and :class:`ValidationFailed` for an empty upload. On any error the
    partial spool is deleted before the exception propagates.
    """
    spool = SpooledUpload(memory_limit=memory_limit, temp_dir=temp_dir)
    try:
        await _fill(spool, stream, max_bytes)
    except BaseException:
        spool.close()
        raise
    return spool


async def _fill(spool: SpooledUpload, stream: AsyncIterator[bytes], max_bytes: int) -> None:
    async for chunk in stream:
        if not chunk:
            continue
        if spool.size + len(chunk) > max_bytes:
            raise PayloadTooLarge(
                f"The file exceeds the maximum upload size of {max_bytes} bytes.",
                internal_detail="upload exceeded max_upload_bytes while streaming",
            )
        await spool.write(chunk)
    spool.seal()
    if spool.size == 0:
        raise ValidationFailed("The uploaded file is empty.")


# --------------------------------------------------------------------------- #
# Sniffing
# --------------------------------------------------------------------------- #
@dataclass(frozen=True, slots=True)
class DetectedType:
    """What the content really is (decided by magic bytes, never by the client)."""

    extension: str
    mime: str
    family: Family
    text_encoding: str | None = None


_MAGIC: Final[tuple[tuple[bytes, str], ...]] = (
    (b"%PDF-", "pdf"),
    (b"PK\x03\x04", "zip"),
    (b"PK\x05\x06", "zip"),
    (b"PK\x07\x08", "zip"),
    (b"\xd0\xcf\x11\xe0\xa1\xb1\x1a\xe1", "ole2"),
    (b"{\\rtf", "rtf"),
    (b"\x7fELF", "executable"),
    (b"\x1f\x8b", "gzip"),
    (b"7z\xbc\xaf\x27\x1c", "7z"),
    (b"Rar!\x1a\x07", "rar"),
    (codecs.BOM_UTF32_LE, "utf32"),
    (codecs.BOM_UTF32_BE, "utf32"),
)


def magic_kind(head: bytes) -> str | None:
    """Name of the binary format ``head`` starts with, or ``None`` if unrecognised."""
    for magic, kind in _MAGIC:
        if head.startswith(magic):
            return kind
    return None


def _mismatch(extension: str, kind: str | None) -> UnsupportedMediaType:
    return UnsupportedMediaType(
        f"The file content does not match its .{extension} extension.",
        internal_detail=f"extension {extension} but content sniffed as {kind or 'unknown'}",
        extra={"reason": "type_mismatch"},
    )


def sniff(head: bytes, extension: str) -> DetectedType:
    """Decide the real type from the leading bytes and check it matches ``extension``.

    PDF must start with ``%PDF-`` at offset 0 (no leading junk: that is how polyglot files
    are built); DOCX/XLSX must be ZIP archives (OLE2 - legacy or password-protected Office
    files - is refused with a specific message); text formats must not start with any known
    binary signature and their first bytes must pass the text checks of
    :func:`validate_text` (the whole file is checked later).
    """
    ext = extension.lower().lstrip(".")
    mime = MIME_TYPES.get(ext)
    if mime is None:
        raise _unsupported("extension_not_supported", "This file type is not supported.")
    kind = magic_kind(head)
    if ext == "pdf":
        if kind != "pdf":
            raise _mismatch(ext, kind)
        return DetectedType(ext, mime, "pdf")
    if ext in OOXML_EXTENSIONS:
        if kind == "ole2":
            raise _unsupported(
                "legacy_or_encrypted_office",
                "Legacy (97-2003) and password-protected Office files are not supported. "
                "Save the file as an unprotected .docx or .xlsx and upload it again.",
            )
        if kind != "zip":
            raise _mismatch(ext, kind)
        return DetectedType(ext, mime, "ooxml")
    if kind == "utf32":
        raise _unsupported("unsupported_text_encoding", "Text files must be UTF-8 or UTF-16.")
    if kind is not None:
        raise _mismatch(ext, kind)
    encoding = text_encoding(head)
    checker = _TextChecker(encoding)
    checker.feed(head, final=False)
    checker.verify()
    return DetectedType(ext, mime, "text", encoding)


def text_encoding(head: bytes) -> str:
    """Codec for a text upload: BOM-marked UTF-8/UTF-16, otherwise UTF-8."""
    if head.startswith(codecs.BOM_UTF8):
        return "utf-8-sig"
    if head.startswith((codecs.BOM_UTF16_LE, codecs.BOM_UTF16_BE)):
        return "utf-16"
    return "utf-8"


# --------------------------------------------------------------------------- #
# Text validation
# --------------------------------------------------------------------------- #
MAX_CONTROL_RATIO: Final = 0.01
CONTROL_SLACK: Final = 8
# C0 controls except TAB, LF, FF and CR; DEL; C1 controls. Built with chr() on purpose.
_CONTROL_CHARS = re.compile(
    "["
    + chr(0x00)
    + "-"
    + chr(0x08)
    + chr(0x0B)
    + chr(0x0E)
    + "-"
    + chr(0x1F)
    + chr(0x7F)
    + "-"
    + chr(0x9F)
    + "]"
)
_NUL = chr(0)


@dataclass(frozen=True, slots=True)
class TextStats:
    characters: int
    control_characters: int


class _TextChecker:
    def __init__(self, encoding: str) -> None:
        self._decoder = codecs.getincrementaldecoder(encoding)(errors="strict")
        self.characters = 0
        self.controls = 0

    def feed(self, data: bytes, *, final: bool) -> None:
        try:
            text = self._decoder.decode(data, final)
        except UnicodeDecodeError as exc:
            raise _unsupported(
                "invalid_text_encoding",
                "The file is not valid UTF-8 or UTF-16 text.",
            ) from exc
        if _NUL in text:
            raise _unsupported(
                "binary_content", "The file contains binary data and is not a text file."
            )
        self.characters += len(text)
        self.controls += len(_CONTROL_CHARS.findall(text))

    def verify(self) -> TextStats:
        if self.controls > CONTROL_SLACK and self.controls > self.characters * MAX_CONTROL_RATIO:
            raise _unsupported(
                "control_characters",
                "The file contains too many control characters to be a text file.",
            )
        return TextStats(self.characters, self.controls)


def validate_text(chunks: Iterable[bytes], encoding: str) -> TextStats:
    """Decode the whole file strictly with ``encoding``.

    Rejects undecodable bytes, any NUL character, and more than :data:`CONTROL_SLACK`
    control characters when they also exceed :data:`MAX_CONTROL_RATIO` of all characters
    (TAB, LF, CR and FF are allowed).
    """
    checker = _TextChecker(encoding)
    for chunk in chunks:
        checker.feed(chunk, final=False)
    checker.feed(b"", final=True)
    return checker.verify()


# --------------------------------------------------------------------------- #
# ZIP / OOXML inspection
# --------------------------------------------------------------------------- #
@dataclass(frozen=True, slots=True)
class ZipLimits:
    max_entries: int
    max_uncompressed_bytes: int
    max_ratio: int


@dataclass(frozen=True, slots=True)
class ZipInspection:
    entry_count: int
    total_uncompressed: int
    total_compressed: int
    package_type: str
    main_content_type: str


RATIO_FLOOR_BYTES: Final = 1024 * 1024
"""Compression ratios are only enforced for entries (and archives) at least this large:
tiny XML parts routinely compress by large factors and cannot hurt anyone."""

MAX_CONTENT_TYPES_BYTES: Final = 1024 * 1024
_MAX_ENTRY_NAME = 1024
_EOCD_SIGNATURE = b"PK\x05\x06"
_EOCD64_LOCATOR_SIGNATURE = b"PK\x06\x07"
_EOCD64_SIGNATURE = b"PK\x06\x06"
_EOCD_SIZE = 22
_EOCD64_LOCATOR_SIZE = 20
_EOCD64_MIN_SIZE = 56
_MAX_ZIP_COMMENT = 0xFFFF
_ZIP_ENCRYPTED_FLAGS = 0x0001 | 0x0040  # traditional + strong encryption
_S_IFMT = 0o170000
_S_IFLNK = 0o120000
_DRIVE_PREFIX = re.compile(r"^[A-Za-z]:")
_ENTRY_CONTROL = re.compile("[" + chr(0x00) + "-" + chr(0x1F) + chr(0x7F) + "]")
_NESTED_ARCHIVE_EXTENSIONS: Final = frozenset(
    {
        "zip", "jar", "war", "ear", "apk", "7z", "rar", "gz", "tgz", "bz2", "xz", "zst",
        "tar", "cab", "iso", "lzh", "arj", "msi", "epub",
        "docx", "docm", "dotx", "dotm", "xlsx", "xlsm", "xltx", "xltm", "xlsb", "xlam",
        "pptx", "pptm", "potx", "potm", "ppsx", "ppsm", "odt", "ods", "odp",
    }
)  # fmt: skip

_PACKAGE_MAIN_TYPES: Final[dict[str, str]] = {
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml": "docx",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml": "xlsx",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template.main+xml": "dotx",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template.main+xml": "xltx",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml": "pptx",
}
_MACRO_CONTENT_TYPE_MARKERS: Final = ("macroenabled", "vbaproject", "vnd.ms-office.vba")


def _corrupt(detail: str) -> RejectedContent:
    return RejectedContent(
        "The file is not a valid Office document.",
        internal_detail=f"corrupt archive: {detail}",
        extra={"reason": "corrupt_archive"},
    )


def declared_entry_count(handle: BinaryIO) -> int:
    """Entry count from the end-of-central-directory record (ZIP64 aware).

    Read *before* :class:`zipfile.ZipFile` materialises one ``ZipInfo`` per entry, so an
    archive declaring millions of entries is refused without allocating for them.
    """
    handle.seek(0, os.SEEK_END)
    size = handle.tell()
    window = min(size, _EOCD_SIZE + _MAX_ZIP_COMMENT)
    handle.seek(size - window)
    tail = handle.read(window)
    pos = tail.rfind(_EOCD_SIGNATURE)
    if pos < 0 or len(tail) - pos < _EOCD_SIZE:
        raise _corrupt("end of central directory not found")
    fields = struct.unpack("<4s4H2LH", tail[pos : pos + _EOCD_SIZE])
    total_entries: int = fields[4]
    if total_entries != 0xFFFF:
        return total_entries
    eocd_offset = size - window + pos
    if eocd_offset < _EOCD64_LOCATOR_SIZE:
        raise _corrupt("zip64 locator missing")
    handle.seek(eocd_offset - _EOCD64_LOCATOR_SIZE)
    locator = handle.read(_EOCD64_LOCATOR_SIZE)
    signature, _disk, record_offset, _disks = struct.unpack("<4sLQL", locator)
    if signature != _EOCD64_LOCATOR_SIGNATURE or record_offset >= size:
        raise _corrupt("zip64 locator invalid")
    handle.seek(record_offset)
    record = handle.read(_EOCD64_MIN_SIZE)
    if len(record) < _EOCD64_MIN_SIZE or record[:4] != _EOCD64_SIGNATURE:
        raise _corrupt("zip64 end of central directory invalid")
    (total64,) = struct.unpack("<Q", record[32:40])
    return int(total64)


def _check_entry_name(raw_name: str) -> None:
    if not raw_name or len(raw_name) > _MAX_ENTRY_NAME:
        raise _rejected("zip_bad_entry_name", "The archive contains an invalid entry name.")
    if _ENTRY_CONTROL.search(raw_name):
        raise _rejected("zip_bad_entry_name", "The archive contains an invalid entry name.")
    if "\\" in raw_name or raw_name.startswith("/") or _DRIVE_PREFIX.match(raw_name):
        raise _rejected("zip_path_traversal", "The archive contains an unsafe path.")
    if any(part == ".." for part in raw_name.split("/")):
        raise _rejected("zip_path_traversal", "The archive contains an unsafe path.")


def _is_symlink(info: zipfile.ZipInfo) -> bool:
    return (info.external_attr >> 16) & _S_IFMT == _S_IFLNK


def _is_nested_archive(name: str) -> bool:
    return extension_of(name.rsplit("/", 1)[-1]) in _NESTED_ARCHIVE_EXTENSIONS


def classify_content_types(xml: bytes) -> tuple[str, str]:
    """Return ``(package_type, main_content_type)`` from ``[Content_Types].xml``.

    Parsed with ``defusedxml`` (DTDs, entity expansion and external references forbidden).
    Any macro-enabled or VBA content type rejects the package outright, whatever its
    file extension claims.
    """
    try:
        root = SafeElementTree.fromstring(xml, forbid_dtd=True)
    except (SafeElementTree.ParseError, DefusedXmlException, ValueError) as exc:
        raise _corrupt(f"content types unreadable: {type(exc).__name__}") from exc
    content_types: list[str] = []
    for element in root.iter():
        tag = element.tag if isinstance(element.tag, str) else ""
        if tag.rsplit("}", 1)[-1] in {"Default", "Override"}:
            value = element.get("ContentType")
            if value:
                content_types.append(value.strip().lower())
    if any(m in ct for ct in content_types for m in _MACRO_CONTENT_TYPE_MARKERS):
        raise _rejected(
            "ooxml_macro_enabled",
            "Macro-enabled Office documents are not accepted.",
        )
    mains = {_PACKAGE_MAIN_TYPES[ct] for ct in content_types if ct in _PACKAGE_MAIN_TYPES}
    if len(mains) != 1:
        raise _unsupported(
            "not_office_document", "The file is not a Word (.docx) or Excel (.xlsx) document."
        )
    package_type = mains.pop()
    main = next(ct for ct in content_types if _PACKAGE_MAIN_TYPES.get(ct) == package_type)
    return package_type, main


def inspect_zip(source: Path | BinaryIO, limits: ZipLimits) -> ZipInspection:
    """Validate an OOXML archive from its metadata; raise on anything unsafe.

    Enforced: declared entry count (checked from the raw EOCD record first), per-entry and
    whole-archive compression ratio (for sizes >= :data:`RATIO_FLOOR_BYTES`), total declared
    uncompressed size, entry names (no absolute, drive-qualified, backslash, ``..`` or
    control-character names; no case-insensitive duplicates, which OPC treats as the same
    part), no encrypted, symlink or nested-archive entries, only stored/deflated entries, and
    a well-formed ``[Content_Types].xml`` naming exactly one Word or Excel main part.
    """
    if isinstance(source, Path):
        with source.open("rb") as handle:
            return _inspect_zip_handle(handle, limits)
    return _inspect_zip_handle(source, limits)


def _inspect_zip_handle(handle: BinaryIO, limits: ZipLimits) -> ZipInspection:
    count = declared_entry_count(handle)
    if count > limits.max_entries:
        raise _rejected("zip_too_many_entries", "The archive contains too many entries.")
    handle.seek(0)
    try:
        archive = zipfile.ZipFile(handle)
    except (zipfile.BadZipFile, zipfile.LargeZipFile, OSError, EOFError, ValueError) as exc:
        raise _corrupt(type(exc).__name__) from exc
    with archive:
        infos = archive.infolist()
        if len(infos) > limits.max_entries:
            raise _rejected("zip_too_many_entries", "The archive contains too many entries.")
        seen: set[str] = set()
        total_uncompressed = 0
        total_compressed = 0
        content_types: zipfile.ZipInfo | None = None
        for info in infos:
            # orig_filename is the name exactly as stored; ZipInfo.filename is truncated at
            # NUL and has backslashes rewritten on Windows, which would hide both tricks.
            _check_entry_name(info.orig_filename)
            key = info.filename.casefold()
            if key in seen:
                raise _rejected("zip_duplicate_entry", "The archive contains duplicate entries.")
            seen.add(key)
            if info.flag_bits & _ZIP_ENCRYPTED_FLAGS:
                raise _rejected("zip_encrypted_entry", "Encrypted archive entries are not allowed.")
            if _is_symlink(info):
                raise _rejected("zip_symlink_entry", "Symbolic links in archives are not allowed.")
            if info.compress_type not in (zipfile.ZIP_STORED, zipfile.ZIP_DEFLATED):
                raise _rejected(
                    "zip_unsupported_compression", "The archive uses an unsupported compression."
                )
            if not info.is_dir() and _is_nested_archive(info.filename):
                raise _rejected("zip_nested_archive", "Nested archives are not allowed.")
            total_uncompressed += info.file_size
            total_compressed += info.compress_size
            if info.file_size >= RATIO_FLOOR_BYTES and info.file_size > limits.max_ratio * max(
                info.compress_size, 1
            ):
                raise _rejected("zip_ratio_exceeded", "The archive is suspiciously compressed.")
            if total_uncompressed > limits.max_uncompressed_bytes:
                raise _rejected(
                    "zip_too_large_uncompressed", "The archive expands to too much data."
                )
            if key == "[content_types].xml":
                content_types = info
        if total_uncompressed >= RATIO_FLOOR_BYTES and total_uncompressed > limits.max_ratio * max(
            total_compressed, 1
        ):
            raise _rejected("zip_ratio_exceeded", "The archive is suspiciously compressed.")
        if content_types is None:
            raise _unsupported(
                "not_office_document",
                "The file is not a Word (.docx) or Excel (.xlsx) document.",
            )
        if content_types.file_size > MAX_CONTENT_TYPES_BYTES:
            raise _corrupt("content types part too large")
        try:
            with archive.open(content_types) as part:
                xml = part.read(MAX_CONTENT_TYPES_BYTES + 1)
        except (zipfile.BadZipFile, OSError, EOFError, RuntimeError, NotImplementedError) as exc:
            raise _corrupt(f"content types unreadable: {type(exc).__name__}") from exc
        package_type, main = classify_content_types(xml)
    return ZipInspection(
        entry_count=len(infos),
        total_uncompressed=total_uncompressed,
        total_compressed=total_compressed,
        package_type=package_type,
        main_content_type=main,
    )


# --------------------------------------------------------------------------- #
# Orchestration
# --------------------------------------------------------------------------- #
@dataclass(frozen=True, slots=True)
class ValidatedContent:
    detected: DetectedType
    archive: ZipInspection | None = None
    text: TextStats | None = None


def validate_content(upload: SpooledUpload, extension: str, limits: ZipLimits) -> ValidatedContent:
    """Run every structural check for ``extension`` over a sealed upload (blocking I/O)."""
    detected = sniff(upload.head, extension)
    if detected.family == "ooxml":
        with upload.open() as handle:
            archive = inspect_zip(handle, limits)
        if archive.package_type != detected.extension:
            raise UnsupportedMediaType(
                f"The file content does not match its .{detected.extension} extension.",
                internal_detail=f"package type {archive.package_type}",
                extra={"reason": "type_mismatch"},
            )
        return ValidatedContent(detected, archive=archive)
    if detected.family == "text":
        stats = validate_text(upload.iter_chunks(), detected.text_encoding or "utf-8")
        return ValidatedContent(detected, text=stats)
    return ValidatedContent(detected)
